#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running tests"
cmd="./vendor/bin/sail run --rm --no-deps laravel.test php artisan test"
$cmd
status=$?
[ $status -eq 0 ] && echo "Tests passed" || exit 1

echo "Running code style fixer"
cmd="./vendor/bin/sail run --rm --no-deps laravel.test composer php-cs-fixer"
$cmd
status=$?
[ $status -eq 0 ] && echo "Pint scan done" || exit 1

echo "Running code analysis"
cmd="./vendor/bin/sail run --rm --no-deps laravel.test composer phpstan"
$cmd
status=$?
[ $status -eq 0 ] && echo "Code analysis done" || exit 1
